### ISSUE TITLE
In Vigyaan Registration form : replace "Leader's college name" with "College Name" 

### ISSUE THREAD

**Issue by Team-Technocracy** [Team-Technocracy/TC-Frontend-aug#6]
Add a line " All Team Members of the team should be from the same college". This line should be added above the registration form.

**Comment by Team-Technocracy** [comment]
also add a line " All Team Members of the team should be from same college" this line should be added above the registration form

**Comment by Piyush-onGIT** [comment]
> also add a line " All Team Members of the team should be from same college" this line should be added above the registration form

@Kraniket901 Please look into this. I am fixing the issue #7

**Comment by Piyush-onGIT** [comment]
> Add a line " All Team Members of the team should be from the same college". This line should be added above the registration form.

@Kraniket901  Please look into this. I am fixing the issue #7
